import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#1768B2",
    padding: 16,
  },
  caixa: {
    width: "80%",
    height: "45%",
    backgroundColor: "#fff",
    borderRadius: 20,
    borderColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
    gap: 45,
  },
  TextInput: {
    borderWidth: 2,
    borderLeftColor: "#fff",
    borderTopColor: "#fff",
    borderRightColor: "#fff",
    borderBottomColor: "#1768B2",
    width: "70%",
    height: 50,
    backgroundColor: "#FFF",
    fontSize: 20,
  },
  button: {
    backgroundColor: "#EBEBEB",
    width: "80%",
    height: "15%",
    alignItems: "center",
    justifyContent: "center",
  },
  buttonText: {
    fontSize: 20,
    color: "#868686",
    fontWeight: "500",
  },
  forgor: {
    color: "#1768B2",
    fontSize: 18,
    textDecorationLine: "underline",
  },
  noticeContainer: {
    marginTop: 20,
    paddingHorizontal: 10,
  },
  noticeHeader: {
    fontSize: 24,
    fontWeight: "bold",
    color: "#fff",
    marginBottom: 20,
    textAlign: "center",
  },
  notice: {
    backgroundColor: "#ffffff90",
    padding: 15,
    borderRadius: 10,
    marginBottom: 10,
  },
  noticeTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#021627",
    borderBottomWidth: 1,
    borderBottomColor: "#021627",
    paddingBottom: 5,
    marginBottom: 5,
  },
  noticeContent: {
    fontSize: 16,
    color: "#021627",
  },
  classesContainer: {
    marginTop: 20,
    paddingHorizontal: 10,
  },
  classesHeader: {
    fontSize: 24,
    fontWeight: "bold",
    color: "#fff",
    marginBottom: 20,
    textAlign: "center",
  },
  classLink: {
    backgroundColor: "#ffffff90",
    padding: 15,
    borderRadius: 10,
    marginBottom: 10,
  },
  classSubject: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#021627",
  },
  classLinkText: {
    fontSize: 16,
    color: "#021627",
    textDecorationLine: "underline",
  },
  eventsContainer: {
    marginTop: 20,
    paddingHorizontal: 10,
  },
  eventsHeader: {
    fontSize: 24,
    fontWeight: "bold",
    color: "#fff",
    marginBottom: 20,
    textAlign: "center",
  },
  event: {
    backgroundColor: "#ffffff90",
    padding: 15,
    borderRadius: 10,
    marginBottom: 10,
  },
  eventTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#021627",
    borderBottomWidth: 1,
    borderBottomColor: "#021627",
    paddingBottom: 5,
    marginBottom: 5,
  },
  eventDate: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#021627",
    marginBottom: 5,
  },
  eventDescription: {
    fontSize: 16,
    color: "#021627",
    marginBottom: 5,
  },
  eventLink: {
    fontSize: 16,
    color: "#021627",
    textDecorationLine: "underline",
    marginBottom: 5,
  },
  card: {
    flex: 1,
    width: "95%",
    backgroundColor: "#ffffff90",
    borderRadius: 10,
    paddingBottom: 20,
  },
  cardTextTitulo: {
    color: '#021627',
    fontSize: 20,
    fontWeight: 'bold',
    margin: 20,
    marginBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#021627',
  },
  cardText: {
    color: '#021627',
    fontSize: 15,
    fontWeight: 'bold',
    marginLeft: 20,
  },
  headerTextName: {
    color: '#fff',
    fontSize: 25,
    fontWeight: 'bold',
    marginTop: 20,
    marginLeft: 20,
    marginBottom: -5,
  },
  headerTextEmail: {
    color: '#fff',
    fontSize: 15,
    fontWeight: 'bold',
    marginLeft: 20,
  },
  icon: {},
});
